spring:
  datasource:
    username: postgres
    password: tNJJAGzmccKZAWPOQQMwcubBxTGcDUQB
    url: jdbc:postgresql://postgres:tNJJAGzmccKZAWPOQQMwcubBxTGcDUQB@tramway.proxy.rlwy.net:33652/railway
    driver-class-name:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  server:
    port: $PORT